language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

script:
 - bin/phpunit
# - bin/behat --format progress

addons:
  apt:
    packages:
    - graphviz

before_script:
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source --dev

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  email:
    - me@mikevanriel.com
    - ashnazg@php.net
